### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by whatever193** [akasakaid/pixelversexyzbot#1]
Traceback (most recent call last):
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main\bot.py", line 180, in <module>
    main()
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main\bot.py", line 175, in main
    client = login(phone)
             ^^^^^^^^^^^^
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main\bot.py", line 56, in login
    client = TelegramClient(f'{session_folder}/{phone}',api_id=api_id,api_hash=api_hash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main\env\Lib\site-packages\telethon\client\telegrambaseclient.py", line 290, in __init__
    session = SQLiteSession(str(session))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main\env\Lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
        ^^^^^^^^^^^^^^
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main\env\Lib\site-packages\telethon\sessions\sqlite.py", line 242, in _cursor
    self._conn = sqlite3.connect(self.filename,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by akasakaid** [comment]
```
git pull
```

i just update the bot.py

**Comment by whatever193** [comment]
Thank you but i see this error
"  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\pixelversexyzbot-main (1)\pixelversexyzbot-main\bot.py", line 118, in bot
    if int(energy) > int(min_energy):
                     ^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"

**Comment by akasakaid** [comment]
are you already copy file `.env.example`to `.env` ??

**Comment by whatever193** [comment]
Sr. My bad, thank you for help

**Comment by akasakaid** [comment]
Okay, you are welcome !!, i will close this issue !
