### ISSUE TITLE
Json decode error help

### ISSUE THREAD

**Issue by Nomanali3468** [akasakaid/pixelversexyzbot#10]
[2024-06-24 10:55:18] account detected : 1        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[2024-06-24 10:55:18] account number : 1
Traceback (most recent call last):                  File "/storage/emulated/0/Download/bots/ptap/bot.py", line 200, in <module>                           app.main()
  File "/storage/emulated/0/Download/bots/ptap/bot.py", line 79, in main
    user = json.loads(data_parse['user'])                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^               File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode            obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                 File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode        raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![Uploading Screenshot_20240624-105554.jpg…]()

**Comment by akasakaid** [comment]
i has update it, try it.
